# Configure LGTM for this package

extraction:
  python:
    python_setup:
      version: 3
path_classifiers:
  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - devtools/*
  generated:
    - mmic_optim_gmx/_version.py
queries:
- exclude: py/not-named-self # Blocks Pydantic's @validator not accepting `self` until a better fix can be found
- exclude: py/missing-equals # Blocks Pydantic's equivalent decorator
